var levels = [
	['             '],
	[' b b b b b b '],
	[' b b b b b b '],
	[' b b bxb b b '],
	[' b b ^ ^ b b '],
	[' ^ ^ , , ^ ^ '],
	[', ,, ^ ^ ,, ,'],
	['` ^^ , , ^^ `'],
	[' , , bbb , , '],
	[' b b b b b b '],
	[' b b ^ ^ b b '],
	[' b b ;,. b b '],
	['     )#(     '],
]